name: creole_companion
description: "Creole Companion - English â†” Haitian Creole Translator"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlite3: ^2.9.3
  cupertino_icons: ^1.0.8
  speech_to_text: ^6.6.1
  audioplayers: ^6.1.0   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/citadelle.jpg
    - assets/images/ile_a_rat.jpg
    - assets/images/port_salut.jpg
    - assets/audio/le_mal_du_pays.mp3   


